const unavailable = document.querySelector('#service-unavailable');
const signedOut = document.querySelector('#signed-out');
const signedIn = document.querySelector('#signed-in');
const message = document.querySelector('#account-message');
let ownedProfiles = [];
let connections = [];
const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[character]);
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { accept: 'application/json', ...(options.body ? { 'content-type': 'application/json' } : {}), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(data.error || 'request_failed'); error.status = response.status; throw error; } return data; }
function showState(name) { unavailable.hidden = name !== 'unavailable'; signedOut.hidden = name !== 'signed-out'; signedIn.hidden = name !== 'signed-in'; const pill = document.querySelector('.service-pill'); pill.classList.toggle('offline', name === 'unavailable'); pill.classList.toggle('ready', name !== 'unavailable'); document.querySelector('#service-label').textContent = name === 'unavailable' ? 'Accounts not active' : name === 'signed-out' ? 'Account service ready' : 'Signed in'; }
function privateDraft() { try { const data = JSON.parse(localStorage.getItem('arctura_profile_draft_v1')); return data?.status === 'local-draft' ? data : null; } catch { return null; } }
function renderDraft() { const draft = privateDraft(); const container = document.querySelector('#draft-import'); container.hidden = !draft; if (draft) document.querySelector('#draft-name').textContent = draft.name || 'Untitled profile'; }
function renderProfiles() { const container = document.querySelector('#owned-profiles'); if (!ownedProfiles.length) { container.innerHTML = '<div class="empty-panel"><h3>No account profiles yet.</h3><p>Add your private browser draft or create a new one.</p></div>'; return; } container.innerHTML = ownedProfiles.map((profile) => `<article class="owned-profile"><header><span>${escapeHtml(profile.profile_type)}</span><small>${escapeHtml(profile.visibility)}</small></header><h3>${escapeHtml(profile.name)}</h3><p>${escapeHtml(profile.headline)}</p><footer><span>/${escapeHtml(profile.handle)}</span><span>${profile.capabilities.length} skills · ${Number(profile.evidence_count) || 0} sources</span></footer><button type="button" class="profile-source-button" data-evidence-profile="${escapeHtml(profile.id)}">Manage sources</button></article>`).join(''); container.querySelectorAll('[data-evidence-profile]').forEach((button) => button.addEventListener('click', () => openEvidence(button.dataset.evidenceProfile))); }
async function openEvidence(profileId) { const profile = ownedProfiles.find((item) => item.id === profileId); if (!profile) return; document.querySelector('#evidence-profile-id').value = profile.id; document.querySelector('#evidence-title').textContent = profile.name; document.querySelector('#evidence-editor').hidden = false; document.querySelector('#evidence-editor').scrollIntoView({ behavior: 'smooth', block: 'start' }); await loadEvidence(profile.id); }
async function loadEvidence(profileId) { const container = document.querySelector('#profile-evidence'); container.innerHTML = '<p>Loading sources…</p>'; try { const result = await api(`/api/profiles/${encodeURIComponent(profileId)}/evidence`); container.innerHTML = result.evidence.length ? `<h4>Current sources</h4>${result.evidence.map((item) => `<article><div><strong>${escapeHtml(item.label)}</strong><span>${escapeHtml(item.review_status.replaceAll('-', ' '))}</span></div><p>${escapeHtml(item.claim)}</p><a href="${escapeHtml(item.url)}" target="_blank" rel="noopener noreferrer">Open source ↗</a></article>`).join('')}` : '<p>No sources attached yet.</p>'; } catch { container.innerHTML = '<p>Sources could not be loaded. Try again.</p>'; } }
async function addEvidence(event) { event.preventDefault(); const profileId = document.querySelector('#evidence-profile-id').value; const payload = { label: document.querySelector('#evidence-label').value, url: document.querySelector('#evidence-url').value, claim: document.querySelector('#evidence-claim').value }; try { await api(`/api/profiles/${encodeURIComponent(profileId)}/evidence`, { method: 'POST', body: JSON.stringify(payload) }); event.currentTarget.reset(); message.textContent = 'Source added as member submitted.'; await loadMemberData(); await openEvidence(profileId); } catch { message.textContent = 'That source could not be added. Check the URL and required fields.'; } }
function actionButtons(connection) { const owned = new Set(ownedProfiles.map((profile) => profile.id)); if (connection.status === 'pending' && owned.has(connection.recipient_id)) return `<button class="primary" data-connection="${connection.id}" data-status="accepted">Accept</button><button data-connection="${connection.id}" data-status="declined">Decline</button><button data-connection="${connection.id}" data-status="blocked">Block</button>`; if (connection.status === 'pending' && owned.has(connection.requester_id)) return `<button data-connection="${connection.id}" data-status="withdrawn">Withdraw</button>`; if (connection.status === 'accepted') return `<button data-connection="${connection.id}" data-status="blocked">Block</button>`; return ''; }
function renderConnections() { const container = document.querySelector('#connection-list'); document.querySelector('#connection-total').textContent = String(connections.length); if (!connections.length) { container.innerHTML = '<div class="empty-panel"><h3>No connection requests yet.</h3><p>Connections begin with a reason, not a follower count.</p><a class="text-link" href="/network/">Find collaborators →</a></div>'; return; } const owned = new Set(ownedProfiles.map((profile) => profile.id)); container.innerHTML = connections.map((connection) => { const incoming = owned.has(connection.recipient_id); const otherName = incoming ? connection.requester_name : connection.recipient_name; const direction = incoming ? 'Request from' : 'Request to'; return `<article class="connection-item"><div><header><span>${direction} · ${escapeHtml(connection.status)}</span></header><h3>${escapeHtml(otherName)}</h3><p>${escapeHtml(connection.reason)}</p></div><div class="connection-actions">${actionButtons(connection)}</div></article>`; }).join(''); container.querySelectorAll('[data-connection]').forEach((button) => button.addEventListener('click', () => changeConnection(button.dataset.connection, button.dataset.status))); }
async function changeConnection(id, nextStatus) { try { await api(`/api/connections/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify({ status: nextStatus }) }); message.textContent = `Connection marked ${nextStatus}.`; await loadMemberData(); } catch { message.textContent = 'That connection could not be updated. Refresh and try again.'; } }
async function publishDraft() { const draft = privateDraft(); if (!draft) return; if (!draft.handle || !draft.name || !draft.headline || !draft.capabilities?.length) { message.textContent = 'Finish the required profile fields before adding this draft.'; return; } const payload = { profileType: draft.profileType, handle: draft.handle, name: draft.name, headline: draft.headline, introduction: draft.introduction, locationMode: draft.locationMode, availability: draft.availability, visibility: 'draft', accountableOwner: draft.agentLimits?.responsibleOwner || '', authorityLimits: draft.agentLimits?.actionsAndLimits || '', capabilities: draft.capabilities }; try { await api('/api/profiles', { method: 'POST', body: JSON.stringify(payload) }); localStorage.removeItem('arctura_profile_draft_v1'); message.textContent = 'Draft added to your account. It is still private.'; renderDraft(); await loadMemberData(); } catch (error) { message.textContent = error.message === 'handle_unavailable' ? 'That profile handle is already in use.' : 'The draft could not be added. Review it and try again.'; } }
async function loadMemberData() { const [profilesResult, connectionsResult] = await Promise.all([api('/api/me/profiles'), api('/api/connections')]); ownedProfiles = profilesResult.profiles; connections = connectionsResult.connections; renderProfiles(); renderConnections(); renderDraft(); }
async function start() { try { const result = await api('/api/session'); showState('signed-in'); document.querySelector('#account-name').textContent = result.account.github_login; await loadMemberData(); } catch (error) { if (error.status === 401) showState('signed-out'); else showState('unavailable'); } }
document.querySelectorAll('[data-tab]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-tab]').forEach((item) => item.setAttribute('aria-selected', String(item === button))); document.querySelectorAll('.account-panel').forEach((panel) => { panel.hidden = panel.id !== `panel-${button.dataset.tab}`; }); }));
document.querySelector('#publish-draft').addEventListener('click', publishDraft);
document.querySelector('#evidence-form').addEventListener('submit', addEvidence);
document.querySelector('#close-evidence').addEventListener('click', () => { document.querySelector('#evidence-editor').hidden = true; });
async function signOut() { try { await api('/api/auth/logout', { method: 'POST' }); location.reload(); } catch { message.textContent = 'Sign out failed. Refresh and try again.'; } }
document.querySelector('#sign-out').addEventListener('click', signOut);
document.querySelector('#settings-sign-out').addEventListener('click', signOut);
document.querySelector('#delete-confirmation').addEventListener('input', (event) => { document.querySelector('#delete-account').disabled = event.target.value !== 'DELETE'; });
document.querySelector('#delete-account').addEventListener('click', async () => { const button = document.querySelector('#delete-account'); if (document.querySelector('#delete-confirmation').value !== 'DELETE') return; button.disabled = true; button.textContent = 'Deleting…'; try { await api('/api/account', { method: 'DELETE', body: JSON.stringify({ confirmation: 'DELETE' }) }); localStorage.removeItem('arctura_profile_draft_v1'); location.replace('/network/?account-deleted=1'); } catch { button.disabled = false; button.textContent = 'Delete account'; message.textContent = 'The account could not be deleted. Refresh and try again.'; } });
start();
