import fs from 'node:fs';
export const origin = 'https://arctura.network';
export const edition = '2026-09-27';
export const esc = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const json = value => JSON.stringify(value).replaceAll('<','\\u003c');
export const arrow = '<span aria-hidden="true">↗</span>';
const navItems = [['/briefings/','Briefings'],['/guides/','Guides'],['/tools/','Tools'],['/evidence/','Evidence'],['/resources/','For agents']];
export function navigation(route) {
  const links = navItems.map(([url,label]) => `<a href="${url}"${route.startsWith(url) ? ' aria-current="'+(route===url?'page':'true')+'"' : ''}>${label}</a>`).join('');
  return `<header class="site-header"><div class="wrap nav-row"><a class="brand" href="/" aria-label="Arctura Network home"><img src="/assets/favicon.svg" alt="" width="34" height="34"><span>ARCTURA <span class="brand-sub">NETWORK</span></span></a><nav class="desktop-nav" aria-label="Primary">${links}</nav><a class="search-link" href="/search/" aria-label="Search Arctura"><svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></a><a class="button button-small desktop-cta" href="/start/">Start here ${arrow}</a><button class="menu-button" type="button" aria-expanded="false" aria-controls="mobile-nav"><span class="sr-only">Open menu</span><span></span><span></span></button></div><nav class="mobile-nav" id="mobile-nav" aria-label="Mobile" hidden>${links}<a href="/start/">Start here</a><a href="/search/">Search the site</a></nav></header>`;
}
export function footer() {
 return `<footer class="site-footer"><div class="wrap footer-grid"><div class="footer-brand"><a class="brand" href="/"><img src="/assets/favicon.svg" alt="" width="34" height="34"><strong>ARCTURA.NETWORK</strong></a><p>Understand the change.<br>Bound the work. Keep the proof.</p><a href="/about/">About Arctura ${arrow}</a><nav class="social-links" aria-label="Official Arctura channels"><a href="https://www.instagram.com/arctura.network/" rel="me noopener">Instagram</a><a href="https://x.com/ArcturaNetwork" rel="me noopener">X</a><a href="https://share.google/K0L9x8JHH3nojsPn9" rel="me noopener">Google</a></nav></div><div><h2>Understand</h2><a href="/briefings/">Briefings</a><a href="/guides/">Practical guides</a><a href="/work-standard/">Work Standard</a><a href="/agents/">Agent Field Guide</a><a href="/insights/">Field Notes</a><a href="/faq/">FAQ</a></div><div><h2>Put it to work</h2><a href="/tools/">All tools</a><a href="/tools/agent-readiness-check/">Readiness Check</a><a href="/tools/agent-accountability-card/">Accountability Card</a><a href="/tools/work-order/">Work Order</a><a href="/tools/media-evidence-desk/">Media Evidence Desk</a><a href="/examples/agents/support-review/">Worked example</a></div><div><h2>Inspect & connect</h2><a href="/evidence/">Evidence library</a><a href="/resources/">Agent resources</a><a href="/network/">Network preview</a><a href="/participate/">Contribute</a><a href="/editorial-policy/">Editorial policy</a><a href="/feed.xml">RSS feed</a></div></div><div class="wrap footer-bottom"><span>© <span id="year">2026</span> Arctura Network</span><span>Work. Proof. Stewardship.</span><a href="https://github.com/virtualmase/arctura.network">Open source ${arrow}</a></div></footer>`;
}
export function page({route,title,description,body,type='WebPage',extra=[],scripts=[],noindex=false}) {
 const url=origin+route;
 const graph=[{'@type':type,'@id':url+'#webpage',url,name:title,description,inLanguage:'en-US',isPartOf:{'@id':origin+'/#website'},publisher:{'@id':origin+'/#organization'}},...extra];
 if(route!=='/')graph.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:origin+'/'},{'@type':'ListItem',position:2,name:title,item:url}]});
 return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — Arctura Network</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><meta name="theme-color" content="#f4f3eb"><link rel="canonical" href="${url}"><link rel="icon" href="/assets/favicon.svg"><link rel="sitemap" type="application/xml" href="/sitemap.xml"><link rel="alternate" type="application/rss+xml" href="/feed.xml" title="Arctura briefings and guides"><link rel="alternate" type="application/feed+json" href="/feed.json" title="Arctura JSON Feed"><link rel="alternate" type="text/plain" href="/llms.txt" title="Site summary"><meta property="og:type" content="${type==='Article'?'article':'website'}"><meta property="og:url" content="${url}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${origin}/assets/experience/social-card.png"><meta property="og:site_name" content="Arctura Network"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${origin}/assets/experience/social-card.png"><script type="application/ld+json">${json({'@context':'https://schema.org','@graph':graph})}</script><link rel="stylesheet" href="/css/site.css"><link rel="stylesheet" href="/css/experience.css"><script src="/js/site.js" defer></script>${scripts.map(s=>`<script src="${s}" defer></script>`).join('')}</head><body class="experience"><a class="skip-link" href="#main">Skip to content</a>${navigation(route)}<main id="main">${body}</main>${footer()}</body></html>\n`;
}
export const intro = (eyebrow,title,description,extra='') => `<section class="page-intro wrap"><p class="kicker">${eyebrow}</p><h1>${title}</h1><p class="intro-deck">${description}</p>${extra}</section>`;
export const routeFor = article => `/${article.kind==='Guide'?'guides':'briefings'}/${article.slug}/`;
export function card(article,index=0) {
 return `<article class="editorial-card" data-filter-item data-topic="${esc(article.topic)}"><a class="card-art art-${index%4}" href="${routeFor(article)}" tabindex="-1" aria-hidden="true"><span class="art-label">${esc(article.topic)}</span><span class="art-orbit"></span><span class="art-node node-a"></span><span class="art-node node-b"></span><span class="art-glyph">${['↗','≋','↔','+'][index%4]}</span><span class="art-caption">WORK / PROOF / STEWARDSHIP</span></a><div class="card-copy"><p class="meta">${esc(article.kind)} <span>·</span> ${esc(article.topic)}</p><h3><a href="${routeFor(article)}">${esc(article.title)}</a></h3><p>${esc(article.description)}</p><a class="card-link" href="${routeFor(article)}">Read ${article.kind.toLowerCase()} ${arrow}</a></div></article>`;
}
export function write(route, html) {const file=route==='/'?'index.html':route.slice(1)+'index.html';fs.mkdirSync(file.slice(0,file.lastIndexOf('/'))||'.',{recursive:true});fs.writeFileSync(file,html);}
